<a href="https://colab.research.google.com/github/raina1234-a/Reddit-Post-Analysis-and-Moderation-Classifier/blob/main/reddit_postClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import pandas as pd
import numpy as np

In [13]:
df = pd.read_csv("/content/r_dataisbeautiful_posts.csv")

In [14]:
df

,id,title,score,author,author_flair_text,removed_by,total_awards_received,awarders,created_utc,full_link,num_comments,over_18
0,it7yz2,[OC] The World’s Forests Mapped,1.0,vividmaps,NaN,NaN,0.0,[],1.600174e+09,https://www.reddit.com/r/dataisbeautiful/comme...,1.0,False
1,it7uig,[OC] Airbnb presence mapped in Barcelona (BCN)...,1.0,JonnieNeptune,OC: 2,NaN,0.0,[],1.600173e+09,https://www.reddit.com/r/dataisbeautiful/comme...,0.0,False
2,it7t4z,A marketplace for open streaming data sources,1.0,DangerMouse289,NaN,automod_filtered,0.0,[],1.600173e+09,https://www.reddit.com/r/dataisbeautiful/comme...,0.0,False
3,it7jfq,[OC] Black Owner-Occupied Housing,1.0,SocialExplorerInc,OC: 17,NaN,0.0,[],1.600172e+09,https://www.reddit.com/r/dataisbeautiful/comme...,1.0,False
4,it7a3r,[OC] My monthly average steps in 2020. Quarant...,1.0,ahmedgelemli,OC: 2,NaN,0.0,[],1.600171e+09,https://www.reddit.com/r/dataisbeautiful/comme...,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...
9019,hddyfh,UK: who goes to college,1.0,AlreadyHasCorona,NaN,moderator,0.0,[],1.592772e+09,https://www.reddit.com/r/dataisbeautiful/comme...,3.0,False
9020,hddy4x,[OC] if chaz was a country it is the most dang...,1.0,Mongoliankonga,NaN,NaN,0.0,[],1.592771e+09,https://www.reddit.com/r/dataisbeautiful/comme...,3.0,False
9021,hddwep,If chaz was a country it is the most dangerous...,1.0,Mongoliankonga,NaN,moderator,0.0,[],1.592771e+09,https://www.reddit.com/r/dataisbeautiful/comme...,2.0,False
9022,hddviq,Half the population of Poland lives in just un...,1.0,RichardPwnsner,NaN,NaN,0.0,[],1.592771e+09,https://www.reddit.com/r/dataisbeautiful/comme...,1.0,False
9023,hdduny,Half the populati,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
df.columns

Index(['id', 'title', 'score', 'author', 'author_flair_text', 'removed_by',
       'total_awards_received', 'awarders', 'created_utc', 'full_link',
       'num_comments', 'over_18'],
      dtype='object')

In [16]:
df.shape

(9024, 12)

In [17]:
df.describe()

              score  total_awards_received   created_utc  num_comments
count   9023.000000            9023.000000  9.023000e+03   9023.000000
mean      58.023496               0.016846  1.596372e+09     45.730023
std     1429.677037               0.511608  2.144827e+06    364.031967
min        0.000000               0.000000  1.592771e+09      0.000000
25%        1.000000               0.000000  1.594515e+09      1.000000
50%        1.000000               0.000000  1.596289e+09      2.000000
75%        1.000000               0.000000  1.598252e+09      7.000000
max    69779.000000              30.000000  1.600174e+09  12508.000000

In [18]:
df.isna().sum()

id                          0
title                       0
score                       1
author                      1
author_flair_text        6762
removed_by               5011
total_awards_received       1
awarders                    1
created_utc                 1
full_link                   1
num_comments                1
over_18                     1
dtype: int64

In [19]:
df.dropna(subset=['title'],inplace=True)

In [20]:
df.drop(["author_flair_text","created_utc","awarders"],axis=1,inplace=True)

In [21]:
df.removed_by.value_counts()

removed_by
moderator           2933
deleted              653
automod_filtered     223
reddit               204
Name: count, dtype: int64

In [22]:
df.removed_by.notnull().sum()

np.int64(4013)

In [23]:
df.over_18.value_counts()

over_18
False    8970
True       53
Name: count, dtype: int64

In [24]:
df.total_awards_received.fillna(0,inplace=True)

/tmp/ipykernel_1567/976138776.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.total_awards_received.fillna(0,inplace=True)

In [25]:
df.isna().sum()

id                          0
title                       0
score                       1
author                      1
removed_by               5011
total_awards_received       0
full_link                   1
num_comments                1
over_18                     1
dtype: int64

In [26]:
df.fillna("NOT DELETED",inplace=True)

/tmp/ipykernel_1567/3051926611.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'NOT DELETED' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.fillna("NOT DELETED",inplace=True)

In [27]:
df.isna().sum()

id                       0
title                    0
score                    0
author                   0
removed_by               0
total_awards_received    0
full_link                0
num_comments             0
over_18                  0
dtype: int64

In [28]:
df

,id,title,score,author,removed_by,total_awards_received,full_link,num_comments,over_18
0,it7yz2,[OC] The World’s Forests Mapped,1.0,vividmaps,NOT DELETED,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,1.0,False
1,it7uig,[OC] Airbnb presence mapped in Barcelona (BCN)...,1.0,JonnieNeptune,NOT DELETED,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,0.0,False
2,it7t4z,A marketplace for open streaming data sources,1.0,DangerMouse289,automod_filtered,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,0.0,False
3,it7jfq,[OC] Black Owner-Occupied Housing,1.0,SocialExplorerInc,NOT DELETED,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,1.0,False
4,it7a3r,[OC] My monthly average steps in 2020. Quarant...,1.0,ahmedgelemli,NOT DELETED,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,0.0,False
...,...,...,...,...,...,...,...,...,...
9019,hddyfh,UK: who goes to college,1.0,AlreadyHasCorona,moderator,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,3.0,False
9020,hddy4x,[OC] if chaz was a country it is the most dang...,1.0,Mongoliankonga,NOT DELETED,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,3.0,False
9021,hddwep,If chaz was a country it is the most dangerous...,1.0,Mongoliankonga,moderator,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,2.0,False
9022,hddviq,Half the population of Poland lives in just un...,1.0,RichardPwnsner,NOT DELETED,0.0,https://www.reddit.com/r/dataisbeautiful/comme...,1.0,False
9023,hdduny,Half the populati,NOT DELETED,NOT DELETED,NOT DELETED,0.0,NOT DELETED,NOT DELETED,NOT DELETED

In [29]:
df.groupby("author").sum()["total_awards_received"].sort_values(ascending=False)

author
PieChartPirate         30.0
Spooderman89           27.0
asherfergusson         18.0
_The_Mattmatician      14.0
MakeYourMarks           8.0
                       ...
Rafaeld007              0.0
RadishBadish            0.0
Radan8                  0.0
Racin_Statistics_YT     0.0
RamboTerminator         0.0
Name: total_awards_received, Length: 4541, dtype: float64

In [40]:
df["num_comments"] = pd.to_numeric(df["num_comments"], errors="coerce")
df.groupby("author")["num_comments"].sum().sort_values(ascending=False)

author
V1Analytics       20725.0
bgregory98        14791.0
asherfergusson    12508.0
PieChartPirate    11182.0
pdwp90            10655.0
                   ...
mrrobot79             0.0
mostafaelmahdy        0.0
music_wired           0.0
naelshiab             0.0
nadod44               0.0
Name: num_comments, Length: 4541, dtype: float64

In [41]:
df["score"] = pd.to_numeric(df["score"], errors="coerce")
df.groupby("author").sum()["score"].sort_values(ascending=False)

author
_The_Mattmatician       69779.0
BoMcCready              55918.0
MakeYourMarks           51813.0
IGuessYourSubreddits    39896.0
Onhech                  32626.0
                         ...
CleverName8888              0.0
Chillyboivinyl              0.0
Bal_Pnuh                    0.0
AtalantaTheRanger           0.0
Atom_alchemist              0.0
Name: score, Length: 4541, dtype: float64

In [42]:
df["over_18"] = pd.to_numeric(df["over_18"], errors="coerce")
df.groupby("author").sum()["over_18"].sort_values(ascending=False)

author
licensecrack        4.0
687962726973        3.0
CRACKTHERE          3.0
DrBrisketNP         3.0
katzenpippi         2.0
                   ...
Ralph_Cane          0.0
Rajesh_Velaga       0.0
Ragtag_fleet        0.0
Rafail17            0.0
RandomSerbianGuy    0.0
Name: over_18, Length: 4541, dtype: float64

In [34]:
df.groupby(["over_18","removed_by"]).count()

                                id  title  score  author  \
over_18     removed_by
False       NOT DELETED       4987   4987   4987    4987
            automod_filtered   220    220    220     220
            deleted            651    651    651     651
            moderator         2916   2916   2916    2916
            reddit             196    196    196     196
True        NOT DELETED         23     23     23      23
            automod_filtered     3      3      3       3
            deleted              2      2      2       2
            moderator           17     17     17      17
            reddit               8      8      8       8
NOT DELETED NOT DELETED          1      1      1       1

                              total_awards_received  full_link  num_comments  \
over_18     removed_by
False       NOT DELETED                        4987       4987          4987
            automod_filtered                    220        220           220
            deleted                             651        651           651
            moderator                          2916       2916          2916
            reddit                              196        196           196
True        NOT DELETED                          23         23            23
            automod_filtered                      3          3             3
            deleted                               2          2             2
            moderator                            17         17            17
            reddit                                8          8             8
NOT DELETED NOT DELETED                           1          1             1

                              adult_18
over_18     removed_by
False       NOT DELETED              0
            automod_filtered       220
            deleted                651
            moderator             2916
            reddit                 196
True        NOT DELETED              0
            automod_filtered         3
            deleted                  2
            moderator               17
            reddit                   8
NOT DELETED NOT DELETED              0

In [35]:
df.corr(numeric_only=True)

                       total_awards_received  adult_18
total_awards_received                    1.0       NaN
adult_18                                 NaN       NaN

In [36]:
df["adult_18"] = 0
df["adult_18"] = df["over_18"].apply(lambda row: 0 if row==False else 1)

In [37]:
df["adult_18"].value_counts()

adult_18
0    8970
1      54
Name: count, dtype: int64

In [38]:
for i in range(0,len(df)):
  if df.loc[i,"removed_by"] != "NOT DELETED":
    df.loc[i,"adult_18"] = 1

In [51]:
import nltk
nltk.download("stopwords")
nltk.download("punkt_tab")
nltk.download("wordnet")

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [59]:
import nltk
import string
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer

def preprocess_text(text):
    text = text.lower()

    tokens = word_tokenize(text)

    tokens = [word for word in tokens if word not in string.punctuation]

    stop_words = set(stopwords.words('english'))
    filtered_tokens = [word for word in tokens if word not in stop_words]

    stemmer = PorterStemmer()
    stemmed_tokens = [stemmer.stem(word) for word in filtered_tokens]

    return ' '.join(stemmed_tokens)
text = "The students are studying machine learning and they are learning new concepts."

result = preprocess_text(text)

print(result)

student studi machin learn learn new concept